import os

PLAN_CRITIQUE_MAX_REVISIONS = int(os.getenv("PLAN_CRITIQUE_MAX_REVISIONS", "2"))
PLAN_CRITIQUE_SCORE_THRESHOLD = int(os.getenv("PLAN_CRITIQUE_SCORE_THRESHOLD", "8"))
EVAL_MAX_EXTRA_ROUNDS = int(os.getenv("EVAL_MAX_EXTRA_ROUNDS", "2"))
EVAL_MAX_GAP_SEARCHES = int(os.getenv("EVAL_MAX_GAP_SEARCHES", "5"))
ENABLE_PLAN_CRITIQUE = os.getenv("ENABLE_PLAN_CRITIQUE", "1") == "1"
ENABLE_RESEARCH_EVAL = os.getenv("ENABLE_RESEARCH_EVAL", "1") == "1"
AGENT_CALL_TIMEOUT_S = float(os.getenv("AGENT_CALL_TIMEOUT_S", "180"))
ENABLE_WRITER_CRITIQUE = os.getenv("ENABLE_WRITER_CRITIQUE", "1") == "1"
WRITER_CRITIQUE_MAX_REVISIONS = int(os.getenv("WRITER_CRITIQUE_MAX_REVISIONS", "2"))
WRITER_CRITIQUE_SCORE_THRESHOLD = int(os.getenv("WRITER_CRITIQUE_SCORE_THRESHOLD", "8"))
